package com.heytap.mspsdk.constants;

/* JADX INFO: loaded from: C:\Users\MR\AppData\Local\Temp\yixiaotong-dex\3873424.dex */
public class MspSdkCode {
    public static final int CODE_CANCEL_DOWNLOAD_APK_FILE_BY_URSER = 3006;
    public static final int CODE_DOWNLOADING_OR_INSTALLING = 3008;
    public static final int CODE_FAILED_DOWNLOAD_APK_FILE = 3005;
    public static final int CODE_FAILED_DOWNLOAD_BY_INSUFFICIENT_STORAGE = 3007;
    public static final int CODE_FAILED_GET_DOWNLOAD_INFO = 3003;
    public static final int CODE_FAILED_VERIFIED_APK_FILE = 3004;
    public static final int CODE_INSTALL_APP_SUC = 3009;
    public static final int CODE_METHOD_CALL_EXCEPTION = 3011;
    public static final int CODE_NOT_FOREGROUND_APP = 3000;
    public static final int CODE_NOT_SUPPORT_KITINFP_SERVICE = 3010;
    public static final int CODE_NO_NETWORK = 3001;
    public static final int CODE_REFLECT_EXCEPTION = 3012;
    public static final int CODE_REFUSE_GUIDE = 3002;
    public static final int CODE_RESULT_RECEIVER_MSP_CORE_ACTIVITY = 1000;
    public static final int EXCEPTION_CODE_2000_DOWN_APP = 2000;
    public static final int EXCEPTION_CODE_2001_DOWN_APP = 2001;
    public static final int EXCEPTION_CODE_2002_MISS_MSP_APP_MIN_VERSION = 2002;
    public static final int EXCEPTION_CODE_2003_MISS_SDK_KIT_NAME = 2003;
    public static final int EXCEPTION_CODE_2004_IPC_BUNDLE_NULL = 2004;
    public static final int EXCEPTION_CODE_2005_NOT_INSTALL_MSP = 2005;
    public static final int EXCEPTION_CODE_2006_NO_EXIST_GUIDE_SDK = 2006;
    public static final int EXCEPTION_CODE_2007_NO_VALID_ANNOTATION = 2007;
    public static final int EXCEPTION_CODE_2008_METHOD_ERROR_TYPE = 2008;
    public static final String EXCEPTION_MSG_2000_DOWN_APP = "installing msp core app";
    public static final String EXCEPTION_MSG_2001_DOWN_APP = "installing the newest msp core app";
    public static final String EXCEPTION_MSG_2002_MISS_MSP_APP_MIN_VERSION = "missing value of msp_app_min_versioncode in your client bundle";
    public static final String EXCEPTION_MSG_2003_MISS_SDK_KIT_NAME = "missing value of msp_sdk_kit_name in your client bundle";
    public static final String EXCEPTION_MSG_2004_IPC_BUNDLE_NULL = "bundle of IPC is null";
    public static final String EXCEPTION_MSG_2005_NOT_INSTALL_MSP = "msp app no exist, showDownloadGuide's value is not 1";
    public static final String EXCEPTION_MSG_2006_NO_EXIST_GUIDE_SDK = "guide sdk no exist";
    public static final String EXCEPTION_MSG_2007_ANNOTATION_ERROR = "module interface annotation config error";
    public static final String EXCEPTION_MSG_2007_INTERFACE_ERROR = "target is not a interface class";
    public static final String EXCEPTION_MSG_2007_NO_VALID_ANNOTATION = "module interface has no valid annotation";
    public static final String EXCEPTION_MSG_2008_METHOD_NOT_MATCH = "module method not match";
    public static final String EXCEPTION_MSG_2008_METHOD_NO_ANNOTATION = "module method no valid annotation";
    public static final String MSG_CANCEL_DOWNLOAD_APK_FILE_BY_URSER = "canceled to download apk file by user";
    public static final String MSG_DOWNLOADING_OR_INSTALLING = "downloading or installing";
    public static final String MSG_FAILED_DOWNLOAD_APK_FILE = "failed to download apk file";
    public static final String MSG_FAILED_DOWNLOAD_BY_INSUFFICIENT_STORAGE = "insufficient storage";
    public static final String MSG_FAILED_GET_DOWNLOAD_INFO = "failed to pull download info";
    public static final String MSG_FAILED_VERIFIED_APK_FILE = "failed to verify apk file";
    public static final String MSG_INSTALL_APP_SUC = "successful to install app";
    public static final String MSG_NOT_FOREGROUND_APP = "not foreground app";
    public static final String MSG_NO_NETWORK = "no available network";
    public static final String MSG_REFUSE_GUIDE = "refused to download by user";
    public static final String MSP_CODE_METHOD_CALL_EXCEPTION = "method call exception";
    public static final String MSP_CODE_REFLECT_EXCEPTION = "reflect exception";
    public static final String MSP_NOT_SUPPORT_KITINFP_SERVICE = "not support kit info service";
}
