package com.kwad.sdk.core.b.a;

import com.kwad.components.core.innerEc.InnerEcUserLoginBindInfo;
import com.kwad.components.core.innerEc.logger.BaseInnerEcMsg;
import com.kwad.components.core.innerEc.logger.InnerEcError;
import com.kwad.components.core.innerEc.logger.InnerEcEvent;
import com.kwad.components.core.innerEc.qcpx.ReceiveQcpxBody;
import com.kwad.components.core.pfmonitor.model.DiskReportInfo;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveMessageListener;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveShopListener;
import com.kwad.components.core.webview.jshandler.WebCardVideoPositionHandler;
import com.kwad.sdk.kgeo.KGeoInfo;
import com.kwad.sdk.mobileid.UaidInfo;
import com.kwad.sdk.monitor.MediaMessageInfo;
import com.kwad.sdk.resourceCache.model.WarmUpReportMessage;

/* JADX INFO: loaded from: C:\Users\MR\AppData\Local\Temp\yixiaotong-dex\6393804.dex */
public final class di {
    public static void LS() {
        hl.LT().put(com.kwad.components.core.webview.jshandler.q.a.class, new iw());
        hl.LT().put(com.kwad.components.core.offline.moitor.d.class, new nq());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.h.class, new ds());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.j.class, new fx());
        hl.LT().put(com.kwad.components.core.m.a.class, new v());
        hl.LT().put(BaseInnerEcMsg.class, new cb());
        hl.LT().put(com.kwad.components.core.webview.a.a.b.class, new eg());
        hl.LT().put(com.kwad.components.core.webview.jshandler.v.b.class, new mq());
        hl.LT().put(com.kwad.components.core.video.a.d.b.class, new ny());
        hl.LT().put(com.kwad.components.core.webview.jshandler.ap.a.class, new hg());
        hl.LT().put(com.kwad.components.core.webview.a.b.class, new jp());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.d.class, new bt());
        hl.LT().put(com.kwad.sdk.monitor.b.C0765b.class, new ll());
        hl.LT().put(com.kwad.components.core.innerEc.live.config.net.c.class, new hw());
        hl.LT().put(com.kwad.components.core.innerEc.live.config.net.g.class, new ig());
        hl.LT().put(com.kwad.components.core.webview.jshandler.j.a.class, new fu());
        hl.LT().put(WebCardVideoPositionHandler.VideoPosition.class, new oc());
        hl.LT().put(com.kwad.components.core.webview.jshandler.ah.a.class, new kh());
        hl.LT().put(com.kwad.components.core.webview.jshandler.ap.b.class, new hh());
        hl.LT().put(com.kwad.components.core.webview.jshandler.ak.a.class, new gg());
        hl.LT().put(com.kwad.components.core.webview.jshandler.as.a.class, new jx());
        hl.LT().put(com.kwad.components.core.webview.jshandler.au.b.class, new bm());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.g.class, new cu());
        hl.LT().put(com.kwad.components.core.innerEc.live.base.d.class, new lh());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.e.class, new cj());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.n.class, new iy());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.s.class, new lr());
        hl.LT().put(com.kwad.components.core.webview.jshandler.e.b.class, new gj());
        hl.LT().put(com.kwad.components.core.webview.jshandler.a.a.C0696a.class, new cl());
        hl.LT().put(MediaMessageInfo.class, new is());
        hl.LT().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.class, new ae());
        hl.LT().put(com.kwad.components.core.webview.jshandler.y.a.class, new x());
        hl.LT().put(ReceiveQcpxBody.class, new ko());
        hl.LT().put(com.kwad.components.core.webview.jshandler.f.a.class, new fq());
        hl.LT().put(com.kwad.sdk.a.a.a.a.class, new gw());
        hl.LT().put(InnerEcError.class, new go());
        hl.LT().put(com.kwad.components.core.webview.a.a.C0692a.class, new ed());
        hl.LT().put(com.kwad.components.core.webview.jshandler.u.a.class, new mu());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.o.class, new jq());
        hl.LT().put(com.kwad.components.core.webview.a.c.class, new jr());
        hl.LT().put(com.kwad.components.core.page.c.a.class, new hu());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.b.class, new bn());
        hl.LT().put(com.kwad.components.core.innerEc.live.config.net.d.class, new hx());
        hl.LT().put(com.kwad.components.core.b.b.class, new hr());
        hl.LT().put(com.kwad.components.core.offline.moitor.b.class, new jo());
        hl.LT().put(com.kwad.components.core.webview.jshandler.a.f.a.class, new cq());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.x.class, new nv());
        hl.LT().put(WebCardRegisterLiveShopListener.AdLiveItemShopInfo.class, new ad());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.b.x.a.class, new bp());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.p.class, new jv());
        hl.LT().put(com.kwad.components.core.pfmonitor.model.b.class, new eb());
        hl.LT().put(com.kwad.components.core.innerEc.live.a.d.a.class, new hz());
        hl.LT().put(com.kwad.components.core.webview.jshandler.bg.a.class, new ge());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.c.class, new br());
        hl.LT().put(com.kwad.components.core.innerEc.live.config.net.e.class, new ic());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.t.class, new ls());
        hl.LT().put(com.kwad.components.core.innerEc.live.f.a.class, new lt());
        hl.LT().put(com.kwad.components.core.innerEc.live.config.net.f.class, new id());
        hl.LT().put(com.kwad.components.core.innerEc.live.base.c.class, new lg());
        hl.LT().put(com.kwad.components.core.innerEc.live.f.b.class, new lu());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.q.class, new kd());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.y.class, new nz());
        hl.LT().put(DiskReportInfo.class, new ea());
        hl.LT().put(com.kwad.components.core.innerEc.followuser.b.class, new ff());
        hl.LT().put(com.kwad.components.core.webview.jshandler.at.a.class, new bi());
        hl.LT().put(com.kwad.components.core.webview.jshandler.aj.a.class, new ns());
        hl.LT().put(WebCardVideoPositionHandler.VideoPosition.KSAdJSCornerModel.class, new ho());
        hl.LT().put(com.kwad.components.core.pfmonitor.model.a.class, new dz());
        hl.LT().put(com.kwad.sdk.monitor.b.a.class, new lk());
        hl.LT().put(com.kwad.components.core.innerEc.live.config.net.a.class, new et());
        hl.LT().put(com.kwad.components.core.innerEc.live.base.b.class, new ib());
        hl.LT().put(com.kwad.components.core.innerEc.live.config.net.i.class, new oj());
        hl.LT().put(com.kwad.components.core.innerEc.live.a.a.C0666a.class, new iu());
        hl.LT().put(com.kwad.components.core.video.a.e.class, new og());
        hl.LT().put(com.kwad.components.core.webview.jshandler.l.a.class, new fw());
        hl.LT().put(com.kwad.components.core.webview.jshandler.an.a.class, new dl());
        hl.LT().put(com.kwad.components.core.innerEc.followuser.a.class, new fe());
        hl.LT().put(com.kwad.components.core.webview.jshandler.bf.a.class, new nd());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.a.class, new o());
        hl.LT().put(com.kwad.components.core.webview.jshandler.ba.a.class, new ih());
        hl.LT().put(com.kwad.components.core.webview.jshandler.a.C0695a.class, new an());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.f.class, new cr());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.u.class, new lv());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.k.class, new hi());
        hl.LT().put(UaidInfo.class, new nn());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.z.class, new od());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.r.class, new lp());
        hl.LT().put(com.kwad.components.core.webview.jshandler.i.a.class, new ft());
        hl.LT().put(InnerEcEvent.class, new gp());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.v.class, new mj());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.b.h.b.class, new kf());
        hl.LT().put(KGeoInfo.class, new hm());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.w.class, new nr());
        hl.LT().put(MediaMessageInfo.MediaPermissionInfo.class, new it());
        hl.LT().put(com.kwad.components.core.webview.jshandler.be.a.class, new oe());
        hl.LT().put(com.kwad.components.core.webview.jshandler.m.a.class, new gu());
        hl.LT().put(com.kwad.components.core.webview.jshandler.bj.a.class, new hk());
        hl.LT().put(com.kwad.components.core.video.a.d.a.class, new nx());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.b.u.b.class, new mk());
        hl.LT().put(com.kwad.components.core.webview.jshandler.ay.a.class, new oh());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.m.class, new hv());
        hl.LT().put(com.kwad.components.core.pfmonitor.model.f.class, new kr());
        hl.LT().put(InnerEcUserLoginBindInfo.class, new gr());
        hl.LT().put(com.kwad.components.core.innerEc.live.base.e.class, new li());
        hl.LT().put(com.kwad.components.core.webview.jshandler.m.b.class, new gv());
        hl.LT().put(com.kwad.components.core.webview.jshandler.ag.a.class, new kg());
        hl.LT().put(com.kwad.components.core.webview.jshandler.ao.b.class, new fz());
        hl.LT().put(com.kwad.components.core.innerEc.live.a.m.a.class, new ec());
        hl.LT().put(com.kwad.components.core.innerEc.live.config.net.b.class, new hp());
        hl.LT().put(com.kwad.components.core.webview.jshandler.au.a.class, new bl());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.i.class, new fa());
        hl.LT().put(com.kwad.components.core.webview.jshandler.av.a.class, new bu());
        hl.LT().put(com.kwad.components.core.webview.jshandler.h.a.class, new fs());
        hl.LT().put(com.kwad.components.core.webview.jshandler.a.c.class, new jh());
        hl.LT().put(com.kwad.components.core.webview.jshandler.a.e.a.class, new lm());
        hl.LT().put(WarmUpReportMessage.class, new of());
        hl.LT().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.AdLiveMessageItemInfo.class, new af());
        hl.LT().put(com.kwad.components.core.webview.jshandler.g.a.class, new fr());
        hl.LT().put(com.kwad.components.core.webview.jshandler.j.b.class, new fv());
        hl.LT().put(com.kwad.components.core.innerEc.live.a.o.a.class, new ht());
        hl.LT().put(com.kwad.components.core.webview.jsPublicBridge.a.a.C0694a.class, new hn());
    }
}
