package com.kwad.sdk.core.b.a;

import com.ksad.annotation.invoker.ForInvoker;
import com.kwad.sdk.commercial.convert.AdLinkMonitorMsg;
import com.kwad.sdk.commercial.model.HybridLoadMsg;
import com.kwad.sdk.commercial.model.SDKInitMsg;
import com.kwad.sdk.commercial.model.WebCloseStatus;
import com.kwad.sdk.commercial.model.WebViewCommercialMsg;
import com.kwad.sdk.commercial.model.WebViewLoadMsg;
import com.kwad.sdk.core.imageloader.ImageLoaderInfo;
import com.kwad.sdk.core.request.model.StatusInfo;
import com.kwad.sdk.core.response.model.ABParams;
import com.kwad.sdk.core.response.model.AdCouponReceiveParam;
import com.kwad.sdk.core.response.model.AdGlobalConfigInfo;
import com.kwad.sdk.core.response.model.AdInfo;
import com.kwad.sdk.core.response.model.AdMatrixInfo;
import com.kwad.sdk.core.response.model.AdProductInfo;
import com.kwad.sdk.core.response.model.AdStatusInfo;
import com.kwad.sdk.core.response.model.AdStyleInfo;
import com.kwad.sdk.core.response.model.AdTemplate;
import com.kwad.sdk.core.response.model.AdVideoPreCacheConfig;
import com.kwad.sdk.core.response.model.CouponInfo;
import com.kwad.sdk.core.response.model.FeedSlideConf;
import com.kwad.sdk.core.response.model.HttpDnsInfo;
import com.kwad.sdk.core.response.model.LiveDetailReward;
import com.kwad.sdk.core.response.model.LiveInfo;
import com.kwad.sdk.core.response.model.LiveRewardInfo;
import com.kwad.sdk.core.response.model.PageInfo;
import com.kwad.sdk.core.response.model.PhotoInfo;
import com.kwad.sdk.core.response.model.TKAdLiveShopItemInfo;
import com.kwad.sdk.core.response.model.TemplateConfig;
import com.kwad.sdk.core.response.model.VideoPlayerStatus;
import com.kwad.sdk.core.scene.URLPackage;
import com.kwad.sdk.internal.api.AdLabelImpl;
import com.kwad.sdk.internal.api.NativeAdExtraDataImpl;
import com.kwad.sdk.internal.api.SceneImpl;
import com.kwad.sdk.internal.api.SplashExtraDataImpl;
import java.util.HashMap;
import java.util.Map;

/* JADX INFO: loaded from: C:\Users\MR\AppData\Local\Temp\yixiaotong-dex\6393804.dex */
public final class hl {
    public static Map<Class<? extends com.kwad.sdk.core.response.a.a>, com.kwad.sdk.core.d> aSG;

    public static Map<Class<? extends com.kwad.sdk.core.response.a.a>, com.kwad.sdk.core.d> LT() {
        return aSG;
    }

    static {
        HashMap map = new HashMap();
        aSG = map;
        map.put(AdInfo.AdRewardInfo.class, new aq());
        aSG.put(AdStyleInfo.PlayDetailInfo.DetailWebCardInfo.class, new dx());
        aSG.put(com.kwad.sdk.commercial.f.b.class, new gb());
        aSG.put(AdMatrixInfo.AggregationCardInfo.class, new be());
        aSG.put(AdMatrixInfo.ComponentTemplateInfo.class, new cx());
        aSG.put(AdMatrixInfo.RewardVideoInteractInfo.class, new la());
        aSG.put(AdStyleInfo.ExtraDisplayInfo.class, new ev());
        aSG.put(AdInfo.class, new y());
        aSG.put(AdInfo.UnDownloadConf.class, new no());
        aSG.put(NativeAdExtraDataImpl.class, new iz());
        aSG.put(TKAdLiveShopItemInfo.class, new my());
        aSG.put(SceneImpl.class, new ln());
        aSG.put(AdInfo.RewardFraudVerifyInfo.class, new ku());
        aSG.put(AdStyleInfo.PlayDetailInfo.DrawAdInfo.class, new ej());
        aSG.put(com.kwad.sdk.core.report.j.class, new ep());
        aSG.put(AdInfo.SlideConvertInfo.class, new lw());
        aSG.put(AdMatrixInfo.class, new am());
        aSG.put(AdMatrixInfo.ShakeInfo.class, new lo());
        aSG.put(AdStyleInfo.PlayDetailInfo.PatchEcInfo.class, new ka());
        aSG.put(com.kwad.sdk.core.network.j.class, new jn());
        aSG.put(AdMatrixInfo.InterstitialCardInfo.class, new hb());
        aSG.put(AdGlobalConfigInfo.NeoScanAggregationSceneInfo.class, new ji());
        aSG.put(StatusInfo.SplashAdInfo.class, new mc());
        aSG.put(com.kwad.sdk.commercial.h.a.class, new il());
        aSG.put(WebCloseStatus.class, new oi());
        aSG.put(com.kwad.sdk.h.a.b.class, new jt());
        aSG.put(AdMatrixInfo.NeoVideoInfo.class, new jk());
        aSG.put(AdInfo.AdMaterialInfo.class, new al());
        aSG.put(com.kwad.sdk.commercial.a.b.class, new bk());
        aSG.put(AdInfo.AdBaseInfo.class, new j());
        aSG.put(AdMatrixInfo.TemplateData.class, new ng());
        aSG.put(com.kwad.sdk.commercial.e.b.class, new du());
        aSG.put(com.kwad.sdk.h.a.a.class, new js());
        aSG.put(AdInfo.AdPreloadInfo.class, new ao());
        aSG.put(com.kwad.sdk.commercial.convert.b.class, new n());
        aSG.put(AdGlobalConfigInfo.RefreshToken.class, new kp());
        aSG.put(AdLabelImpl.class, new ab());
        aSG.put(AdInfo.AdTrackInfo.class, new ay());
        aSG.put(AdVideoPreCacheConfig.class, new bb());
        aSG.put(LiveInfo.LiveStreamPlayCDNNode.class, new ii());
        aSG.put(AdInfo.FullScreenVideoInfo.class, new fo());
        aSG.put(com.kwad.sdk.core.threads.b.class, new nh());
        aSG.put(AdInfo.DownloadSafeInfo.class, new ef());
        aSG.put(com.kwad.sdk.core.h.a.C0745a.class, new na());
        aSG.put(AdCouponReceiveParam.class, new p());
        aSG.put(AdMatrixInfo.FullScreenInfo.class, new fn());
        aSG.put(com.kwad.sdk.core.threads.d.class, new ni());
        aSG.put(AdGlobalConfigInfo.CycleAggregationInfo.class, new dr());
        aSG.put(AdMatrixInfo.FeedInfo.class, new ez());
        aSG.put(StatusInfo.class, new mt());
        aSG.put(com.kwad.sdk.commercial.c.a.class, new cc());
        aSG.put(AdStyleInfo.ExposeTagInfo.class, new es());
        aSG.put(AdInfo.AdBannerInfo.class, new i());
        aSG.put(AdInfo.MaterialSize.class, new ip());
        aSG.put(com.kwad.sdk.core.request.model.b.class, new dy());
        aSG.put(AdStyleInfo.PlayDetailInfo.DetailCommonInfo.class, new dv());
        aSG.put(com.kwad.sdk.core.request.model.d.class, new jl());
        aSG.put(AdStyleInfo.class, new av());
        aSG.put(AdMatrixInfo.SlideInfo.class, new lx());
        aSG.put(AdMatrixInfo.StyleComponentInfo.class, new mv());
        aSG.put(HttpDnsInfo.class, new gh());
        aSG.put(LiveInfo.User.class, new nt());
        aSG.put(com.kwad.sdk.core.request.model.g.class, new nu());
        aSG.put(AdMatrixInfo.BottomBannerInfo.class, new ci());
        aSG.put(AdMatrixInfo.DynamicAdStyleInfo.class, new em());
        aSG.put(AdMatrixInfo.RotateDegreeInfo.class, new le());
        aSG.put(AdStyleInfo.PlayEndInfo.class, new ke());
        aSG.put(com.kwad.sdk.commercial.b.b.class, new bo());
        aSG.put(AdInfo.AdMaterialInfo.MaterialFeature.class, new in());
        aSG.put(AdMatrixInfo.NativeMatrixAdInfo.class, new jf());
        aSG.put(StatusInfo.SplashStyleControl.class, new mn());
        aSG.put(AdMatrixInfo.Styles.class, new mx());
        aSG.put(AdMatrixInfo.RewardVideoTaskInfo.class, new lb());
        aSG.put(AdInfo.NativeAdShakeInfo.class, new jc());
        aSG.put(AdInfo.AdLiveTypeInfo.class, new ag());
        aSG.put(com.kwad.sdk.utils.b.a.class, new hs());
        aSG.put(WebViewLoadMsg.class, new ol());
        aSG.put(PhotoInfo.class, new kb());
        aSG.put(AdInfo.CutRuleInfo.class, new dp());
        aSG.put(AdMatrixInfo.SplashEndCardTKInfo.class, new md());
        aSG.put(AdMatrixInfo.PreLandingPageTKInfo.class, new kk());
        aSG.put(AdMatrixInfo.AdInteractionInfo.class, new aa());
        aSG.put(AdMatrixInfo.SplashActionBarInfo.class, new mb());
        aSG.put(AdMatrixInfo.MatrixTag.class, new iq());
        aSG.put(StatusInfo.NativeAdStyleControl.class, new jd());
        aSG.put(AdStyleInfo.PlayDetailInfo.WidgetAdInfo.class, new om());
        aSG.put(AdMatrixInfo.RewardWebTaskCloseInfo.class, new lc());
        aSG.put(AdStyleInfo.PlayEndInfo.EndTopToolBarInfo.class, new eo());
        aSG.put(AdStyleInfo.PlayDetailInfo.DetailTopToolBarInfo.class, new dw());
        aSG.put(AdMatrixInfo.BaseMatrixTemplate.class, new cd());
        aSG.put(AdMatrixInfo.ActionBarInfoNew.class, new d());
        aSG.put(AdInfo.AdvertiserInfo.class, new bd());
        aSG.put(PhotoInfo.BaseInfo.class, new ca());
        aSG.put(CouponInfo.class, new dk());
        aSG.put(AdGlobalConfigInfo.class, new w());
        aSG.put(AdMatrixInfo.InnerEcAuthInfo.class, new gn());
        aSG.put(LiveInfo.class, new ia());
        aSG.put(AdInfo.CallBackStrategyInfo.class, new ck());
        aSG.put(HttpDnsInfo.IpInfo.class, new hf());
        aSG.put(AdStyleInfo.PlayDetailInfo.PatchAdInfo.class, new jz());
        aSG.put(com.kwad.sdk.core.config.d.class, new ju());
        aSG.put(AdMatrixInfo.SplashPlayCardTKInfo.class, new mi());
        aSG.put(AdMatrixInfo.RotateInfo.class, new lf());
        aSG.put(com.kwad.sdk.commercial.d.b.class, new q());
        aSG.put(WebViewCommercialMsg.class, new ok());
        aSG.put(AdInfo.ComplianceInfo.class, new cv());
        aSG.put(AdStatusInfo.class, new at());
        aSG.put(AdInfo.AdFeedInfo.class, new u());
        aSG.put(AdProductInfo.class, new ap());
        aSG.put(AdLinkMonitorMsg.class, new ac());
        aSG.put(AdInfo.UnDownloadRegionConf.class, new np());
        aSG.put(AdInfo.AdDrawInfo.class, new t());
        aSG.put(AdMatrixInfo.MerchantLiveReservationInfo.class, new iv());
        aSG.put(PageInfo.class, new jw());
        aSG.put(ImageLoaderInfo.class, new gl());
        aSG.put(com.kwad.sdk.core.request.model.f.class, new nc());
        aSG.put(AdStyleInfo.PlayDetailInfo.ActionBarInfo.class, new c());
        aSG.put(com.kwad.sdk.commercial.d.c.class, new r());
        aSG.put(AdMatrixInfo.AdDataV2.class, new s());
        aSG.put(LiveDetailReward.class, new hy());
        aSG.put(com.kwad.sdk.commercial.i.a.C0731a.class, new nl());
        aSG.put(AdMatrixInfo.InstalledActivateInfo.class, new gx());
        aSG.put(AdMatrixInfo.DownloadTexts.class, new eh());
        aSG.put(AdStyleInfo.PlayEndInfo.AdWebCardInfo.class, new bc());
        aSG.put(AdMatrixInfo.MatrixTemplate.class, new ir());
        aSG.put(com.kwad.sdk.commercial.i.b.class, new ba());
        aSG.put(HybridLoadMsg.class, new gi());
        aSG.put(AdInfo.NativeAdInfo.class, new ja());
        aSG.put(AdMatrixInfo.SplashInfo.class, new mf());
        aSG.put(PhotoInfo.VideoInfo.class, new nw());
        aSG.put(AdInfo.H5Config.class, new fy());
        aSG.put(AdMatrixInfo.SplashSlideInfo.class, new mm());
        aSG.put(AdMatrixInfo.StyleInfo.class, new mw());
        aSG.put(AdInfo.AdSplashInfo.class, new as());
        aSG.put(AdInfo.AdConversionInfo.DeeplinkItemInfo.class, new dt());
        aSG.put(LiveRewardInfo.class, new Cif());
        aSG.put(com.kwad.sdk.wrapper.l.a.C0772a.class, new mp());
        aSG.put(TemplateConfig.class, new ne());
        aSG.put(AdInfo.SmallAppJumpInfo.class, new ly());
        aSG.put(AdMatrixInfo.ActivityMiddlePageInfo.class, new g());
        aSG.put(LiveInfo.CoverThumbnailUrl.class, new dm());
        aSG.put(AdStyleInfo.FeedAdInfo.class, new ex());
        aSG.put(AdInfo.AdConversionInfo.class, new m());
        aSG.put(VideoPlayerStatus.class, new ob());
        aSG.put(AdInfo.AdAggregateInfo.class, new h());
        aSG.put(AdMatrixInfo.CycleAggregateInfo.class, new dq());
        aSG.put(com.kwad.sdk.core.network.i.class, new jm());
        aSG.put(AdProductInfo.SpikeInfo.class, new ma());
        aSG.put(AdStyleInfo.PlayDetailInfo.class, new kc());
        aSG.put(AdMatrixInfo.MerchantLiveReservationInfo.LiveReservationPlayEndInfo.class, new ie());
        aSG.put(AdTemplate.class, new ax());
        aSG.put(ABParams.class, new a());
        aSG.put(AdMatrixInfo.EndCardInfo.class, new en());
        aSG.put(com.kwad.sdk.wrapper.l.a.class, new on());
        aSG.put(com.kwad.sdk.commercial.smallApp.b.class, new lz());
        aSG.put(AdInfo.PlayableStyleInfo.class, new ki());
        aSG.put(LiveInfo.CoverUrlCdn.class, new dn());
        aSG.put(AdInfo.RewardRetryTaskInfo.class, new kz());
        aSG.put(AdInfo.AdInsertScreenInfo.class, new z());
        aSG.put(AdInfo.AdShowVideoH5Info.class, new ar());
        aSG.put(AdStyleInfo.AdBrowseInfo.class, new l());
        aSG.put(SDKInitMsg.class, new lj());
        aSG.put(StatusInfo.NativeAdRequestInfo.class, new jb());
        aSG.put(AdMatrixInfo.ComponentParam.class, new cw());
        aSG.put(AdInfo.AdStyleConfInfo.class, new au());
        aSG.put(URLPackage.class, new nm());
        aSG.put(FeedSlideConf.class, new fc());
        aSG.put(LiveInfo.User.HeadUrl.class, new gd());
        aSG.put(SplashExtraDataImpl.class, new me());
        LS();
    }

    @ForInvoker(methodId = "registerHolder")
    private static void LS() {
        cy.LS();
        cz.LS();
        da.LS();
        db.LS();
        dc.LS();
        dd.LS();
        de.LS();
        df.LS();
        dg.LS();
        dh.LS();
        di.LS();
        fg.LS();
        fh.LS();
        fi.LS();
        fj.LS();
        fk.LS();
        fl.LS();
    }

    public static com.kwad.sdk.core.d getHolder(Class<? extends com.kwad.sdk.core.response.a.a> cls) {
        return aSG.get(cls);
    }
}
